### ISSUE TITLE
Error with postgres.

### ISSUE THREAD

**Issue by vikingecotours** [CrawlerCode/payload-authjs#8]
error: operator does not exist: character varying = integer
    at <unknown> (.next/server/chunks/596.js:8:154753)
    at async (.next/server/chunks/596.js:108:16936)
    at async c (.next/server/chunks/596.js:119:11308)
    at async Object.s [as findOne] (.next/server/chunks/596.js:119:13024)
    at async d (.next/server/chunks/596.js:628:31102)
    at async ec (.next/server/chunks/3956.js:1:13630)
    at async (.next/server/chunks/596.js:628:29840)
    at async (.next/server/chunks/596.js:628:29786) {
  length: 213,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No operator matches the given name and argument types. You might need to add explicit type casts.',
  position: '649',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_oper.c',
  line: '647',
  routine: 'op_error',
  digest: '3809751229'
}

**Comment by CrawlerCode** [comment]
I have now been able to reproduce it. This happens when your database schema is not correct and is not updated by payload. Then your users.id is a number, but should be a string. I manually deleted the broken users table and after payload created a new one, this problem was fixed.
